    var baraja = [{palo: "Corazones",
                   numero: "AS",
                   valor: 1,
                    },
                  {palo: "Corazones",
                   numero: "DOS",
                   valor: 2,
                    },
                  {palo: "Corazones",
                   numero: "TRES",
                   valor: 3,
                    },
                  {palo: "Corazones",
                   numero: "CUATRO",
                   valor: 4,
                    },
                  {palo: "Corazones",
                   numero: "CINCO",
                   valor: 5,
                    },
                  {palo: "Corazones",
                   numero: "SEIS",
                   valor: 6,
                    },
                  {palo: "Corazones",
                   numero: "SIETE",
                   valor: 7,
                    },
                  {palo: "Corazones",
                   numero: "OCHO",
                   valor: 8,
                    },
                  {palo: "Corazones",
                   numero: "NUEVE",
                   valor: 9,
                    },
                  {palo: "Corazones",
                   numero: "DIEZ",
                   valor: 10,
                    },
                  {palo: "Corazones",
                   numero: "J",
                   valor: 11,
                    },
                  {palo: "Corazones",
                   numero: "Q",
                   valor: 12,
                    },
                  {palo: "Corazones",
                   numero: "K",
                   valor: 13,
                    },
///////////////////////////////////////////////////////////
                  {palo: "Picas",
                   numero: "AS",
                   valor: 1,
                    },
                  {palo: "Picas",
                   numero: "DOS",
                   valor: 2,
                    },
                  {palo: "Picas",
                   numero: "TRES",
                   valor: 3,
                    },
                  {palo: "Picas",
                   numero: "CUATRO",
                   valor: 4,
                    },
                  {palo: "Picas",
                   numero: "CINCO",
                   valor: 5,
                    },
                  {palo: "Picas",
                   numero: "SEIS",
                   valor: 6,
                    },
                  {palo: "Picas",
                   numero: "SIETE",
                   valor: 7,
                    },
                  {palo: "Picas",
                   numero: "OCHO",
                   valor: 8,
                    },
                  {palo: "Picas",
                   numero: "NUEVE",
                   valor: 9,
                    },
                  {palo: "Picas",
                   numero: "DIEZ",
                   valor: 10,
                    },
                  {palo: "Picas",
                   numero: "J",
                   valor: 11,
                    },
                  {palo: "Picas",
                   numero: "Q",
                   valor: 12,
                    },
                  {palo: "Picas",
                   numero: "K",
                   valor: 13,
                    },
///////////////////////////////////////////////////////////
                  {palo: "Treboles",
                   numero: "AS",
                   valor: 1,
                    },
                  {palo: "Treboles",
                   numero: "DOS",
                   valor: 2,
                    },
                  {palo: "Treboles",
                   numero: "TRES",
                   valor: 3,
                    },
                  {palo: "Treboles",
                   numero: "CUATRO",
                   valor: 4,
                    },
                  {palo: "Treboles",
                   numero: "CINCO",
                   valor: 5,
                    },
                  {palo: "Treboles",
                   numero: "SEIS",
                   valor: 6,
                    },
                  {palo: "Treboles",
                   numero: "SIETE",
                   valor: 7,
                    },
                  {palo: "Treboles",
                   numero: "OCHO",
                   valor: 8,
                    },
                  {palo: "Treboles",
                   numero: "NUEVE",
                   valor: 9,
                    },
                  {palo: "Treboles",
                   numero: "DIEZ",
                   valor: 10,
                    },
                  {palo: "Treboles",
                   numero: "J",
                   valor: 11,
                    },
                  {palo: "Treboles",
                   numero: "Q",
                   valor: 12,
                    },
                  {palo: "Treboles",
                   numero: "K",
                   valor: 13,
                    },
///////////////////////////////////////////////////////////
                  {palo: "Diamantes",
                   numero: "AS",
                   valor: 1,
                    },
                  {palo: "Diamantes",
                   numero: "DOS",
                   valor: 2,
                    },
                  {palo: "Diamantes",
                   numero: "TRES",
                   valor: 3,
                    },
                  {palo: "Diamantes",
                   numero: "CUATRO",
                   valor: 4,
                    },
                  {palo: "Diamantes",
                   numero: "CINCO",
                   valor: 5,
                    },
                  {palo: "Diamantes",
                   numero: "SEIS",
                   valor: 6,
                    },
                  {palo: "Diamantes",
                   numero: "SIETE",
                   valor: 7,
                    },
                  {palo: "Diamantes",
                   numero: "OCHO",
                   valor: 8,
                    },
                  {palo: "Diamantes",
                   numero: "NUEVE",
                   valor: 9,
                    },
                  {palo: "Diamantes",
                   numero: "DIEZ",
                   valor: 10,
                    },
                  {palo: "Diamantes",
                   numero: "J",
                   valor: 11,
                    },
                  {palo: "Diamantes",
                   numero: "Q",
                   valor: 12,
                    },
                  {palo: "Diamantes",
                   numero: "K",
                   valor: 13,
                    },
    ];